site_name: betools for Python
site_url: http://bruceeckel.github.io/betools/
repo_url: https://github.com/BruceEckel/betools

pages:
- Home: index.md
- CmdLine: cmdline.md
- VisitDir: visitdir.md
- Ruler: ruler.md
